# Generated by Django 4.1.2 on 2022-11-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_restaurant_closetime_restaurant_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='about',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
