# Generated by Django 4.1.2 on 2022-11-12 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_restaurant_address_alter_restaurant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_bio',
        ),
    ]
