# Generated by Django 4.1.2 on 2022-11-12 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_profile_birth_date_remove_profile_user_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
