# Generated by Django 4.1.2 on 2022-11-12 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='images',
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
