# Generated by Django 4.1.2 on 2022-11-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_tablebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablebooking',
            name='cust_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
