# Generated by Django 4.1.2 on 2022-11-15 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
