# Generated by Django 4.1.2 on 2022-11-15 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_tablebooking_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='img1',
            field=models.ImageField(blank=True, default='static/assets/pexels-ray-01.jpg', null=True, upload_to='static/assets/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='img2',
            field=models.ImageField(blank=True, default='static/assets/pexels-ray-01.jpg', null=True, upload_to='static/assets/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='img3',
            field=models.ImageField(blank=True, default='static/assets/pexels-ray-01.jpg', null=True, upload_to='static/assets/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='img4',
            field=models.ImageField(blank=True, default='static/assets/pexels-ray-01.jpg', null=True, upload_to='static/assets/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='menu',
            field=models.ImageField(blank=True, default='static/assets/pexels-ray-01.jpg', null=True, upload_to='static/assets/'),
        ),
    ]
