# Generated by Django 4.1.2 on 2022-11-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_restaurant_img1_restaurant_img2_restaurant_img3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablebooking',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
